In [1]:
import numpy as np

Using np.array()

In [ ]:
a = np.array([2,3,4])
print(a)
print(a.ndim)

In [21]:
b =np.array([[3,4,5],[6,7,8]])
print(b)
print(b.ndim)

[[3 4 5]
 [6 7 8]]
2


Predefined Funtion


In [34]:
np.zeros((4,6))




array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [30]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [36]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Generating Squuences

In [72]:
np.random.rand(2,3)


array([[0.84592684, 0.13129068, 0.79670337],
       [0.64092752, 0.07500957, 0.97011711]])

In [70]:
np.random.randint(0,10,5)

array([5, 4, 4, 2, 2])

In [74]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [78]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [90]:
arra1 = np.array([[4,5,6],[7,8,9],[4,9,2]])
print(arra1.shape)
print(arra1.ndim)
print(arra1.dtype)
print(arra1.itemsize)
print(arra1.nbytes)

(3, 3)
2
int32
4
36


In [96]:
arr =np.array([[10,20,30],[40,50,60]])
print(arr[0][1])
print(arr[1][2])

20
60


In [98]:
arr[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [100]:
arr[0,:2]

array([10, 20])

In [102]:
arr[: ,1:]

array([[20, 30],
       [50, 60]])

In [104]:
arr[-1,-2]

50

In [108]:
a =np.arange(10)
a[2:7:2]

array([2, 4, 6])

In [112]:
c =np.array([4,5,6])
b =np.array([7,8,2])

print(c + b)
print(c - b)
print(c * b)
print(c / b)
print(c % b)

[11 13  8]
[-3 -3  4]
[28 40 12]
[0.57142857 0.625      3.        ]
[4 5 0]


In [120]:
m = a > 2
n = b == 5
print(m)
print(n)

[False False False  True  True  True  True  True  True  True]
True


In [134]:
s = np.array([5,6,7,8,9])
print(np.sum(s))
print(np.mean(s))
print(np.min(s))
print(np.max(s))
print(np.sqrt(s))
print(np.exp(a))
print(np.log(a))

35
7.0
5
9
[2.23606798 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


C:\Users\PC\AppData\Local\Temp\ipykernel_4928\260333961.py:8: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))


In [130]:
print(np.sin(np.pi/2))

1.0


In [132]:
print(np.cos(0))

1.0
